apiVersion: skaffold/v4beta9
kind: Config
build:
  artifacts:
    - image: daminmutti/auth
      context: auth
    - image: daminmutti/client
      context: client
    - image: daminmutti/tickets
      context: tickets
    - image: daminmutti/orders
      context: orders
    - image: daminmutti/expiration
      context: expiration
    - image: daminmutti/payments
      context: payments
  local:
    push: false
manifests:
  rawYaml:
    - ./infra/k8s/*
    - ./infra/k8s-dev/*
deploy:
  kubectl: {}
