apiVersion: skaffold/v4beta5
kind: Config
build:
  artifacts:
    - image: daminmutti/auth
      context: auth
      docker:
        dockerfile: Dockerfile
    - image: daminmutti/client
      context: client
      docker:
        dockerfile: Dockerfile
    - image: daminmutti/tickets
      context: tickets
      docker:
        dockerfile: Dockerfile
    - image: daminmutti/orders
      context: orders
      docker:
        dockerfile: Dockerfile
    - image: daminmutti/expiration
      context: expiration
      docker:
        dockerfile: Dockerfile
    - image: daminmutti/payments
      context: payments
      docker:
        dockerfile: Dockerfile
  local:
    push: false
manifests:
  rawYaml:
    - ./infra/k8s/*
    - ./infra/k8s-dev/*
deploy:
  kubectl:
    defaultNamespace: default
