name: tests-payments

on:
  pull_request

jobs: 
  build: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'  # Using the latest LTS version that supports structuredClone
      - run: cd payments && npm install && npm run test:ci
